import { useQuery } from '@tanstack/react-query'
import { AlertCircle, ArrowRight, ArrowUpRight, FilePlus2, History, Search, ShieldCheck, UserRound } from 'lucide-react'
import type { AuthUser } from '@/features/auth/authApi'
import { getDashboard } from '@/features/documents/documentsApi'
import { ApiError } from '@/lib/api'
import type { Screen } from '@/navigation'
import { Button } from '@/components/ui/button'

export function HomePage({ user, onNavigate }: { user: AuthUser; onNavigate: (screen: Screen) => void }) {
  const dashboardQuery = useQuery({ queryKey: ['dashboard'], queryFn: getDashboard })
  const scope = user.role === 'ADMIN' ? 'del sistema' : 'personal'
  const errorText = dashboardQuery.error instanceof ApiError && dashboardQuery.error.code ? dashboardQuery.error.message : 'No pudimos cargar el resumen. Intentá nuevamente.'

  return <section className="max-w-[82rem]">
    <header className="motion-reveal border-b-2 border-slate-200 pb-8 sm:pb-10 lg:grid lg:grid-cols-[minmax(0,1fr)_19rem] lg:gap-12"><div className="border-l-4 border-blue-700 pl-4 sm:pl-5"><p className="typo-eyebrow text-blue-700">STIA PBA · Zona 6</p><h1 className="typo-display-xl mt-2 max-w-3xl uppercase">Hola, {user.nombre}</h1><p className="typo-body-lg mt-4 max-w-2xl text-slate-600">Gestioná la documentación gremial con la información que ya tenés disponible.</p><div className="mt-7 flex flex-col gap-3 sm:mt-8 sm:flex-row"><button type="button" onClick={() => onNavigate('new-document')} className="group flex min-h-14 w-full items-center justify-between gap-4 bg-blue-800 px-5 text-left text-white transition-[background-color,transform] duration-200 hover:bg-blue-900 active:translate-y-px focus-visible:ring-2 focus-visible:ring-blue-700 focus-visible:ring-offset-2 sm:w-auto sm:min-w-64 sm:px-6"><span className="flex items-center gap-3"><FilePlus2 size={21} aria-hidden="true" /><span className="typo-control">Crear documento</span></span><ArrowUpRight className="transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" size={21} aria-hidden="true" /></button><Button variant="outline" className="min-h-14 border-blue-200 bg-white sm:px-6" onClick={() => onNavigate('bulk-document')}>Generar varios permisos</Button></div></div><aside className="mt-8 border border-blue-100 bg-blue-50/70 px-5 py-5 lg:mt-0 lg:self-stretch"><p className="typo-eyebrow text-blue-800">Espacio de trabajo</p><p className="typo-body-sm mt-3 max-w-xs text-slate-700">Resumen {scope}. Accedé a las tareas principales desde un solo lugar.</p><div aria-hidden="true" className="mt-7 flex items-end justify-between border-t border-blue-200 pt-4"><span className="typo-meta text-blue-800">Zona 6</span><span className="typo-display-lg leading-none text-blue-200">06</span></div></aside></header>
    {dashboardQuery.isPending ? <DashboardLoading /> : dashboardQuery.isError ? <DashboardError text={errorText} onRetry={() => dashboardQuery.refetch()} /> : <><Summary documentsThisMonth={dashboardQuery.data.documentsThisMonth} totalDocuments={dashboardQuery.data.totalDocuments} role={user.role} /><QuickWork role={user.role} onNavigate={onNavigate} /></>}
  </section>
}

function Summary({ documentsThisMonth, totalDocuments, role }: { documentsThisMonth: number; totalDocuments: number; role: AuthUser['role'] }) {
  const scope = role === 'ADMIN' ? 'Resumen del sistema' : 'Tu resumen'
  if (totalDocuments === 0) return <section className="motion-reveal mt-8 border-y border-slate-200 py-10 sm:mt-10 sm:py-12" aria-labelledby="summary-title"><p className="typo-eyebrow text-blue-700">{scope}</p><h2 id="summary-title" className="typo-display-lg mt-3 uppercase">Todavía no hay actividad</h2><p className="typo-body-sm mt-3 max-w-md text-slate-600">Cuando generes el primer documento, el resumen aparecerá acá.</p></section>
  return <section className="motion-reveal mt-8 border border-slate-200 bg-white sm:mt-10" aria-labelledby="summary-title"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4 sm:px-7"><p className="typo-eyebrow text-blue-800">{scope}</p><h2 id="summary-title" className="typo-heading-2 mt-1">Resumen de actividad</h2></div><dl className="sm:grid sm:grid-cols-[minmax(0,1.45fr)_minmax(16rem,1fr)]"><div className="bg-blue-50/60 px-5 py-6 sm:px-7"><dt className="typo-meta text-slate-600">Documentos este mes</dt><dd className="typo-display-xl mt-1 tabular-nums text-blue-950">{documentsThisMonth}</dd><p className="typo-body-sm mt-1 text-slate-600">{documentsThisMonth === 1 ? 'documento generado' : 'documentos generados'}</p></div><div className="border-t border-slate-200 px-5 py-5 sm:border-l sm:border-t-0 sm:px-7"><dt className="typo-meta text-slate-600">Total de documentos</dt><dd className="typo-display-lg mt-1 tabular-nums text-slate-900">{totalDocuments}</dd><p className="typo-body-sm mt-1 text-slate-600">disponibles en el historial</p></div></dl></section>
}

function QuickWork({ role, onNavigate }: { role: AuthUser['role']; onNavigate: (screen: Screen) => void }) {
  const openSearch = () => window.dispatchEvent(new Event('open-global-search'))
  return <section className="motion-reveal mt-10 sm:mt-12" aria-labelledby="quick-work-title"><div className="flex items-end justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="typo-eyebrow text-slate-500">Acciones</p><h2 id="quick-work-title" className="typo-heading-2 mt-2">Trabajo rápido</h2></div><p className="typo-meta hidden text-slate-500 sm:block">Accesos frecuentes</p></div><div className="mt-5 divide-y divide-slate-200 border border-slate-200 bg-white"><WorkRow icon={Search} title="Buscar documentos" description="Encontrá por número, empresa o delegado." action="Buscar" onClick={openSearch} /><WorkRow icon={History} title="Historial" description="Consultá, descargá o reutilizá documentos." action="Ver" onClick={() => onNavigate('history')} />{role === 'ADMIN' && <WorkRow icon={ShieldCheck} title="Administración" description="Gestioná usuarios, catálogos y plantillas." action="Abrir" onClick={() => onNavigate('admin')} />}<WorkRow icon={UserRound} title="Mi perfil" description="Consultá tu información y opciones de sesión." action="Ver" onClick={() => onNavigate('profile')} /></div></section>
}

function WorkRow({ icon: Icon, title, description, action, onClick }: { icon: typeof Search; title: string; description: string; action: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="group flex min-h-16 w-full items-center gap-4 px-4 py-3 text-left transition-colors hover:bg-blue-50/70 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-blue-600 sm:px-5"><span className="grid h-10 w-10 shrink-0 place-items-center border border-slate-200 bg-slate-50 text-blue-700"><Icon size={18} aria-hidden="true" /></span><span className="min-w-0 flex-1"><strong className="block text-slate-900">{title}</strong><span className="typo-body-sm mt-0.5 block text-slate-600">{description}</span></span><span className="typo-control inline-flex min-h-11 shrink-0 items-center gap-1 text-blue-800 group-hover:text-blue-950">{action} <ArrowRight size={17} aria-hidden="true" /></span></button> }
function DashboardLoading() { return <div className="mt-8 animate-pulse space-y-8" aria-label="Cargando resumen"><div className="h-44 border border-slate-200 bg-slate-100" /><div className="h-56 border border-slate-200 bg-slate-100" /></div> }
function DashboardError({ text, onRetry }: { text: string; onRetry: () => void }) { return <div role="alert" className="mt-8 flex flex-wrap items-center justify-between gap-4 border border-rose-200 bg-rose-50 p-5 text-sm text-rose-900"><span className="flex items-center gap-3"><AlertCircle size={19} aria-hidden="true" />{text}</span><Button variant="outline" onClick={onRetry}>Reintentar resumen</Button></div> }
