import { Plus, X } from 'lucide-react'
import type { ReactNode } from 'react'

export function AdminOverlay({ title, description, children, onClose }: { title: string; description?: string; children: ReactNode; onClose: () => void }) {
  return <div role="dialog" aria-modal="true" aria-labelledby="admin-overlay-title" className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/40 sm:items-center sm:p-4"><section className="max-h-[calc(100dvh-1rem)] w-full max-w-md overflow-y-auto rounded-t-2xl bg-white p-5 pb-[calc(1.25rem+env(safe-area-inset-bottom))] shadow-xl sm:max-h-[85dvh] sm:rounded-2xl sm:p-6"><div className="mx-auto mb-4 h-1.5 w-10 rounded-full bg-slate-300 sm:hidden" /><div className="flex items-start justify-between gap-3"><div><h2 id="admin-overlay-title" className="text-xl font-bold">{title}</h2>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div><button type="button" onClick={onClose} className="grid h-11 w-11 shrink-0 place-items-center rounded-lg text-slate-600 hover:bg-slate-100" aria-label="Cerrar"><X size={20} /></button></div>{children}</section></div>
}

export function AdminConfirmation({ title, message, actionLabel, pending, onCancel, onConfirm, destructive = false, cancelLabel = 'Cancelar' }: { title: string; message: string; actionLabel: string; pending: boolean; onCancel: () => void; onConfirm: () => void; destructive?: boolean; cancelLabel?: string }) {
  return <AdminOverlay title={title} description={message} onClose={onCancel}><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} disabled={pending} className="min-h-11 rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 disabled:opacity-60">{cancelLabel}</button><button type="button" onClick={onConfirm} disabled={pending} className={`min-h-11 rounded-xl px-4 py-2 text-sm font-semibold text-white disabled:opacity-60 ${destructive ? 'bg-rose-700 hover:bg-rose-800' : 'bg-blue-700 hover:bg-blue-800'}`}>{pending ? 'Procesando...' : actionLabel}</button></div></AdminOverlay>
}

export function AdminHeader({ title, description, newLabel, onCreate }: { title: string; description?: string; newLabel: string; onCreate: () => void }) { return <header className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">Administración</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{title}</h1>{description && <p className="mt-1 text-sm text-slate-600">{description}</p>}</div><button type="button" onClick={onCreate} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800"><Plus size={18} />{newLabel}</button></header> }
export function AdminNotice({ kind, children }: { kind: 'success' | 'error'; children: ReactNode }) { return <p role={kind === 'error' ? 'alert' : 'status'} className={`mt-4 rounded-xl border px-4 py-3 text-sm ${kind === 'error' ? 'border-rose-200 bg-rose-50 text-rose-800' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{children}</p> }
export function AdminEmptyState({ children, actionLabel, onAction }: { children: ReactNode; actionLabel: string; onAction: () => void }) { return <div className="py-12 text-center"><p className="text-sm text-slate-600">{children}</p><button type="button" onClick={onAction} className="mt-4 min-h-11 rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700 hover:bg-blue-50">{actionLabel}</button></div> }
