import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, Eye, LoaderCircle } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { downloadDocument } from '@/features/documents/documentActions'
import { filenameFromHeaders } from '@/features/documents/documentsApi'
import { ApiError } from '@/lib/api'
import { downloadMonthlyReport, exportCatalog, exportReport, generateMonthlyReport, getMonthlyReports, getReportSummary, type MonthlyReport } from './reportsApi'

function currentMonth() { const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const last = new Date(now.getFullYear(), now.getMonth() + 1, 0); return { from: first.toISOString().slice(0, 10), to: last.toISOString().slice(0, 10) } }
const quickExports = [{ key: 'companies', label: 'Empresas', description: 'Catálogo administrativo vigente.' }, { key: 'delegates', label: 'Delegados', description: 'Personas con rol delegado.' }, { key: 'agreements', label: 'Convenios', description: 'Códigos y descripciones.' }, { key: 'users', label: 'Usuarios', description: 'Accesos y estados.' }] as const

export function ReportsPage() {
  const queryClient = useQueryClient(); const initial = currentMonth(); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [applied, setApplied] = useState(initial); const [exporting, setExporting] = useState<string | null>(null); const [generating, setGenerating] = useState(false); const [error, setError] = useState(''); const [selectedMonthly, setSelectedMonthly] = useState<MonthlyReport | null>(null)
  const invalid = !from || !to || from > to
  const query = useQuery({ queryKey: ['reports', applied], queryFn: () => getReportSummary(applied.from, applied.to) })
  const monthlyQuery = useQuery({ queryKey: ['monthly-reports'], queryFn: getMonthlyReports })
  const download = async (key: string) => { setError(''); setExporting(key); try { const result = key === 'report' ? await exportReport(applied.from, applied.to) : await exportCatalog(key as typeof quickExports[number]['key']); downloadDocument(result.blob, filenameFromHeaders(result.headers) || `${key}.xlsx`) } catch { setError('No pudimos generar la exportación. Intentá nuevamente.') } finally { setExporting(null) } }
  const generate = async () => { const period = lastClosedMonth(); setError(''); setGenerating(true); try { await generateMonthlyReport(period.year, period.month); await queryClient.invalidateQueries({ queryKey: ['monthly-reports'] }) } catch { setError('No pudimos generar el reporte mensual. Intentá nuevamente.') } finally { setGenerating(false) } }
  const downloadMonthly = async (report: MonthlyReport) => { setError(''); setExporting(`monthly-${report.id}`); try { const result = await downloadMonthlyReport(report.id); downloadDocument(result.blob, filenameFromHeaders(result.headers) || report.filename) } catch { setError('No pudimos descargar el reporte mensual. Intentá nuevamente.') } finally { setExporting(null) } }
  const summary = query.data

  return <section className="max-w-6xl">
    <header className="border-l-4 border-blue-700 pl-4 sm:pl-5"><p className="typo-eyebrow text-blue-700">Administración</p><h1 className="typo-display-xl mt-1 uppercase">Reportes y exportaciones</h1><p className="typo-body-sm mt-3 max-w-xl text-slate-600">Consultá la actividad del sistema y descargá información lista para trabajar o compartir.</p></header>
    <section className="mt-8 border border-slate-200 bg-slate-50/80 p-4 sm:p-5" aria-labelledby="period-title"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><p className="typo-eyebrow text-slate-500">Generar reporte</p><h2 id="period-title" className="typo-heading-2 mt-1">Período</h2></div><p className="typo-meta text-slate-600">Actualizá el resumen antes de exportar.</p></div><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><Label htmlFor="report-from">Desde</Label><Input id="report-from" className="mt-2 border-slate-300 bg-white focus:border-blue-600 focus:ring-blue-100" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div><Label htmlFor="report-to">Hasta</Label><Input id="report-to" className="mt-2 border-slate-300 bg-white focus:border-blue-600 focus:ring-blue-100" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div><Button className="min-h-11 sm:min-w-44" disabled={invalid || query.isFetching} onClick={() => setApplied({ from, to })}>{query.isFetching ? <LoaderCircle className="animate-spin" size={17} /> : null} Actualizar resumen</Button></div>{invalid && <p role="alert" className="mt-3 text-sm text-rose-700">La fecha desde no puede ser posterior a la fecha hasta.</p>}</section>
    {error && <Notice>{error}</Notice>}{query.isError ? <Notice>{query.error instanceof ApiError ? query.error.message : 'No pudimos cargar el resumen.'} <button className="font-semibold underline" onClick={() => query.refetch()}>Reintentar</button></Notice> : query.isPending ? <p className="mt-8 border-y border-slate-200 py-10 text-center text-sm text-slate-500"><LoaderCircle className="mr-2 inline animate-spin" size={17} />Cargando resumen...</p> : summary?.totalDocuments === 0 ? <p className="mt-8 border-y border-slate-200 py-10 text-center text-slate-600">No hay actividad en este período.</p> : summary && <Summary summary={summary} />}
    <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1.2fr)_minmax(22rem,.8fr)] lg:items-start"><section className="border border-slate-200 bg-white p-5 sm:p-6"><p className="typo-eyebrow text-slate-500">Exportar reporte</p><h2 className="typo-heading-2 mt-2">Actividad del período</h2><p className="typo-body-sm mt-2 text-slate-600">Incluye los documentos emitidos entre las fechas aplicadas.</p><Button className="mt-5 min-h-11" disabled={!summary || summary.totalDocuments === 0 || exporting !== null} onClick={() => void download('report')}>{exporting === 'report' ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Exportar reporte</Button></section><section className="border-t border-slate-200 pt-6 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><p className="typo-eyebrow text-slate-500">Exportaciones rápidas</p><h2 className="typo-heading-2 mt-2">Datos administrativos</h2><div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{quickExports.map((item) => <div key={item.key} className="flex min-h-16 items-center gap-3 py-3"><div className="min-w-0 flex-1"><h3 className="font-semibold text-slate-900">{item.label}</h3><p className="text-sm text-slate-600">{item.description}</p></div><Button variant="outline" className="min-h-11 shrink-0" aria-label={`Exportar ${item.label}`} disabled={exporting !== null} onClick={() => void download(item.key)}>{exporting === item.key ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Exportar</Button></div>)}</div></section></div>
    <MonthlyReportsSection reports={monthlyQuery.data} isPending={monthlyQuery.isPending} isError={monthlyQuery.isError} isGenerating={generating} downloadingId={exporting?.replace('monthly-', '') ?? null} onGenerate={() => void generate()} onDownload={(report) => void downloadMonthly(report)} onView={setSelectedMonthly} onRetry={() => monthlyQuery.refetch()} />
    <MonthlyReportDialog report={selectedMonthly} onOpenChange={(open) => { if (!open) setSelectedMonthly(null) }} onDownload={(report) => void downloadMonthly(report)} downloading={exporting === `monthly-${selectedMonthly?.id}`} />
  </section>
}

function Notice({ children }: { children: React.ReactNode }) { return <p role="alert" className="mt-5 border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{children}</p> }
function Summary({ summary }: { summary: { dateFrom: string; dateTo: string; totalDocuments: number; uniqueDelegates: number; uniqueCompanies: number; uniqueAgreements: number } }) { return <section className="mt-8 border border-slate-200 bg-white" aria-labelledby="summary-title"><div className="border-b border-slate-200 bg-slate-50 px-5 py-4 sm:px-6"><p className="typo-eyebrow text-slate-500">Resumen del período</p><h2 id="summary-title" className="typo-meta mt-1 text-slate-600">{formatDate(summary.dateFrom)} al {formatDate(summary.dateTo)}</h2></div><div className="grid sm:grid-cols-[minmax(13rem,.9fr)_repeat(3,1fr)]"><Metric primary label="Documentos generados" value={summary.totalDocuments} /><Metric label="Delegados" value={summary.uniqueDelegates} /><Metric label="Empresas" value={summary.uniqueCompanies} /><Metric label="Convenios" value={summary.uniqueAgreements} /></div></section> }
function Metric({ label, value, primary = false }: { label: string; value: number; primary?: boolean }) { return <div className={`border-t border-slate-200 px-5 py-4 first:border-t-0 sm:border-l sm:first:border-l-0 sm:border-t-0 sm:px-6 ${primary ? 'bg-blue-50/60' : ''}`}><dt className="typo-meta text-slate-600">{label}</dt><dd className={`${primary ? 'typo-display-lg text-blue-900' : 'typo-heading-2'} mt-1 tabular-nums`}>{value}</dd></div> }
function lastClosedMonth() { const now = new Date(); const date = new Date(now.getFullYear(), now.getMonth(), 0); return { year: date.getFullYear(), month: date.getMonth() + 1 } }
function monthLabel(year: number, month: number) { return new Intl.DateTimeFormat('es-AR', { month: 'long', year: 'numeric' }).format(new Date(year, month - 1, 1)).replace(/^./, value => value.toUpperCase()) }
function formatDate(value: string) { return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) }
function formatDateTime(value: string) { return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) }
function MonthlyReportsSection({ reports, isPending, isError, isGenerating, downloadingId, onGenerate, onDownload, onView, onRetry }: { reports: MonthlyReport[] | undefined; isPending: boolean; isError: boolean; isGenerating: boolean; downloadingId: string | null; onGenerate: () => void; onDownload: (report: MonthlyReport) => void; onView: (report: MonthlyReport) => void; onRetry: () => void }) {
  const lastClosed = lastClosedMonth(); const pending = !reports?.some(report => report.periodStart === `${lastClosed.year}-${String(lastClosed.month).padStart(2, '0')}-01`)
  return <section className="mt-8 border-t border-slate-200 pt-8" aria-labelledby="monthly-reports-title"><p className="typo-eyebrow text-slate-500">Archivo histórico</p><h2 id="monthly-reports-title" className="typo-heading-2 mt-2">Reportes mensuales</h2><p className="typo-body-sm mt-2 max-w-xl text-slate-600">Cada período se genera una sola vez y queda disponible para su consulta histórica.</p>{isError ? <Notice>No pudimos cargar los reportes mensuales. <button className="font-semibold underline" onClick={onRetry}>Reintentar</button></Notice> : isPending ? <p className="mt-5 border-y border-slate-200 py-5 text-sm text-slate-500"><LoaderCircle className="mr-2 inline animate-spin" size={17} />Cargando reportes mensuales...</p> : <>{reports?.length === 0 && <p className="mt-5 text-sm text-slate-600">No hay reportes mensuales generados.</p>}<div className="mt-5 border border-slate-200 bg-white">{pending && <div className="border-b border-slate-200 bg-amber-50/50 px-4 py-4 sm:flex sm:items-center sm:justify-between sm:gap-4"><div><p className="font-semibold">{monthLabel(lastClosed.year, lastClosed.month)}</p><p className="mt-1 text-sm text-amber-800">Pendiente de generación</p></div><Button className="mt-3 min-h-11 sm:mt-0" disabled={isGenerating} onClick={onGenerate}>{isGenerating ? <LoaderCircle className="animate-spin" size={17} /> : null} Generar ahora</Button></div>}{reports?.map(report => <div key={report.id} className="flex min-h-20 flex-col gap-3 border-b border-slate-200 px-4 py-4 last:border-b-0 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><h3 className="font-semibold text-slate-900">{monthLabel(Number(report.periodStart.slice(0, 4)), Number(report.periodStart.slice(5, 7)))}</h3><p className="mt-1 inline-flex bg-emerald-50 px-2 py-0.5 typo-caption font-semibold text-emerald-800">Disponible</p><p className="mt-1 text-sm text-slate-600">Generado el {formatDateTime(report.generatedAt)}</p></div><div className="flex gap-2"><Button variant="outline" className="min-h-11" onClick={() => onView(report)}><Eye size={17} /> Ver</Button><Button variant="outline" className="min-h-11" disabled={downloadingId !== null} onClick={() => onDownload(report)}>{downloadingId === report.id ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Descargar</Button></div></div>)}</div></>}</section>
}
function MonthlyReportDialog({ report, onOpenChange, onDownload, downloading }: { report: MonthlyReport | null; onOpenChange: (open: boolean) => void; onDownload: (report: MonthlyReport) => void; downloading: boolean }) { return <Dialog open={report !== null} onOpenChange={onOpenChange}><DialogContent>{report && <><DialogHeader><DialogTitle>Reporte mensual</DialogTitle><DialogDescription>Archivo histórico disponible para descargar.</DialogDescription></DialogHeader><dl className="mt-6 divide-y divide-slate-200 border-y border-slate-200"><Detail label="Período" value={`${formatDate(report.periodStart)} - ${formatDate(report.periodEnd)}`} /><Detail label="Generado" value={formatDateTime(report.generatedAt)} /><Detail label="Archivo" value={report.filename} /></dl><Button className="mt-6 min-h-11 w-full" disabled={downloading} onClick={() => onDownload(report)}>{downloading ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Descargar Excel</Button></>}</DialogContent></Dialog> }
function Detail({ label, value }: { label: string; value: string }) { return <div className="py-3"><dt className="typo-meta text-slate-600">{label}</dt><dd className="mt-1 text-sm font-medium text-slate-900">{value}</dd></div> }
