import { useQuery } from '@tanstack/react-query'
import { Download, LoaderCircle } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { downloadDocument } from '@/features/documents/documentActions'
import { filenameFromHeaders } from '@/features/documents/documentsApi'
import { ApiError } from '@/lib/api'
import { exportCatalog, exportReport, getReportSummary } from './reportsApi'

function currentMonth() { const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const last = new Date(now.getFullYear(), now.getMonth() + 1, 0); return { from: first.toISOString().slice(0, 10), to: last.toISOString().slice(0, 10) } }
const quickExports = [{ key: 'companies', label: 'Empresas', description: 'Catálogo administrativo vigente.' }, { key: 'delegates', label: 'Delegados', description: 'Personas con rol delegado.' }, { key: 'agreements', label: 'Convenios', description: 'Códigos y descripciones.' }, { key: 'users', label: 'Usuarios', description: 'Accesos y estados.' }] as const

export function ReportsPage() {
  const initial = currentMonth(); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [applied, setApplied] = useState(initial); const [exporting, setExporting] = useState<string | null>(null); const [error, setError] = useState('')
  const invalid = !from || !to || from > to
  const query = useQuery({ queryKey: ['reports', applied], queryFn: () => getReportSummary(applied.from, applied.to) })
  const download = async (key: string) => { setError(''); setExporting(key); try { const result = key === 'report' ? await exportReport(applied.from, applied.to) : await exportCatalog(key as typeof quickExports[number]['key']); downloadDocument(result.blob, filenameFromHeaders(result.headers) || `${key}.xlsx`) } catch { setError('No pudimos generar la exportación. Intentá nuevamente.') } finally { setExporting(null) } }
  const summary = query.data
  return <section className="max-w-5xl"><header className="border-b border-slate-200 pb-6"><p className="typo-eyebrow text-blue-700">Administración</p><h1 className="typo-display-xl mt-2 uppercase">Reportes y exportaciones</h1><p className="typo-body-sm mt-3 max-w-xl text-slate-600">Consultá la actividad del sistema y descargá información lista para trabajar o compartir.</p></header>
    <section className="mt-8 border-b border-slate-200 pb-8" aria-labelledby="period-title"><p className="typo-eyebrow text-slate-500">Generar reporte</p><h2 id="period-title" className="typo-heading-2 mt-2">Período</h2><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><Label htmlFor="report-from">Desde</Label><Input id="report-from" className="mt-2" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div><Label htmlFor="report-to">Hasta</Label><Input id="report-to" className="mt-2" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div><Button className="min-h-11" disabled={invalid || query.isFetching} onClick={() => setApplied({ from, to })}>{query.isFetching ? <LoaderCircle className="animate-spin" size={17} /> : null} Actualizar resumen</Button></div>{invalid && <p role="alert" className="mt-3 text-sm text-rose-700">La fecha desde no puede ser posterior a la fecha hasta.</p>}</section>
    {error && <p role="alert" className="mt-5 border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{query.isError ? <p role="alert" className="mt-5 border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{query.error instanceof ApiError ? query.error.message : 'No pudimos cargar el resumen.'} <button className="font-semibold underline" onClick={() => query.refetch()}>Reintentar</button></p> : query.isPending ? <p className="mt-10 text-center text-sm text-slate-500"><LoaderCircle className="mr-2 inline animate-spin" size={17} />Cargando resumen...</p> : summary?.totalDocuments === 0 ? <p className="mt-10 border-y border-slate-200 py-10 text-center text-slate-600">No hay actividad en este período.</p> : summary && <section className="mt-8 border-y border-slate-200 py-7" aria-labelledby="summary-title"><p className="typo-eyebrow text-slate-500">Resumen del período</p><h2 id="summary-title" className="typo-display-lg mt-2 tabular-nums text-blue-900">{summary.totalDocuments}</h2><p className="typo-body-sm text-slate-600">documentos generados</p><dl className="mt-6 grid divide-y divide-slate-200 border-t border-slate-200 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><Metric label="Delegados involucrados" value={summary.uniqueDelegates} /><Metric label="Empresas" value={summary.uniqueCompanies} /><Metric label="Convenios" value={summary.uniqueAgreements} /></dl></section>}
    <section className="mt-8 border-b border-slate-200 pb-8"><p className="typo-eyebrow text-slate-500">Exportar reporte</p><h2 className="typo-heading-2 mt-2">Actividad del período</h2><Button className="mt-5 min-h-11" disabled={!summary || summary.totalDocuments === 0 || exporting !== null} onClick={() => void download('report')}>{exporting === 'report' ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Descargar Excel</Button></section>
    <section className="mt-8"><p className="typo-eyebrow text-slate-500">Exportaciones rápidas</p><h2 className="typo-heading-2 mt-2">Datos administrativos</h2><div className="mt-5 divide-y divide-slate-200 border-y border-slate-200">{quickExports.map((item) => <div key={item.key} className="flex min-h-16 items-center gap-4 py-3"><div className="min-w-0 flex-1"><h3 className="font-semibold">{item.label}</h3><p className="text-sm text-slate-600">{item.description}</p></div><Button variant="outline" className="min-h-11 shrink-0" disabled={exporting !== null} onClick={() => void download(item.key)}>{exporting === item.key ? <LoaderCircle className="animate-spin" size={17} /> : <Download size={17} />} Exportar</Button></div>)}</div></section></section>
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="py-4 sm:px-5 first:pl-0"><dt className="typo-meta text-slate-600">{label}</dt><dd className="typo-heading-2 mt-1 tabular-nums">{value}</dd></div> }
